name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.0.2
                  run_install: true

            - name: Build/release Electron app
              run: pnpm build
              env:
                  GH_TOKEN: ${{ secrets.github_token }}

            - name: Add change log
              if: matrix.platform == 'ubuntu-latest'
              uses: taiki-e/create-gh-release-action@v1
              with:
                  changelog: CHANGELOG.md
                  title: $version
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}
