name: Release

on: push

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2.3.4

            - name: Install Node.js, PNPM
              uses: pnpm/action-setup@v2.0.1

            - name: Install dependencies
              run: pnpm i

            - name: Build/release Electron app
              run: pnpm build
              env:
                  GH_TOKEN: ${{ secrets.github_token }}
