name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Cache modules
              uses: actions/cache@v2
              with:
                  path: ~/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - run: npm install -g yarn

            - name: Changelog
              if: matrix.platform == 'ubuntu-latest'
              run: yarn changelog

            - name: Release
              if: matrix.platform == 'ubuntu-latest'
              uses: taiki-e/create-gh-release-action@v1
              with:
                  changelog: CHANGELOG.md
                  title: $version
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}

            - run: yarn boot
            - if: matrix.os == 'ubuntu-latest'
              run: yarn add 7zip-bin-linux

            - run: yarn build
            - run: yarn package
              env:
                  GH_TOKEN: ${{ secrets.github_token }}
