name: Release

on:
    push:
        tags:
            - '*'

jobs:
    linux:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Cache modules
              uses: actions/cache@v2
              with:
                  path: ~/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: bootstrap 

            - name: Add change log
              if: matrix.os == 'ubuntu-latest'
              uses: taiki-e/create-gh-release-action@v1
              with:
                  changelog: CHANGELOG.md
                  title: $version
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}

            - uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: build
              env:
                  GH_TOKEN: ${{ secrets.github_token }}

    else:
        runs-on: ${{ matrix.os }}
        needs: linux
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Cache modules
              uses: actions/cache@v2
              with:
                  path: ~/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: bootstrap

            - uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: build
              env:
                  GH_TOKEN: ${{ secrets.github_token }}
